# Keyvault test program Makefile

PROGS=		kv_test kv_fdpass_server kv_fdpass_client
CFLAGS+=	-Wall -Wextra -I.. -Wno-unused-parameter
MAN=

SRCS.kv_test=		kv_test.c
SRCS.kv_fdpass_server=	kv_fdpass_server.c
SRCS.kv_fdpass_client=	kv_fdpass_client.c

.include <bsd.progs.mk>
